# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy Vite React app to Azure Web App - chemet-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Upload Vite build output
        uses: actions/upload-artifact@v4
        with:
          name: vite-dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Vite build artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-dist
          path: ./dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D892EF147AE411F8C8AF82EFA8C12A0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4A25FFDA0D7A45FEBA5DC33564DD9094 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_916290CE0EC54C80BB740B8FCED7D5A4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chemet-App'
          slot-name: 'Production'
          package: ./dist
